# Generated by Django 5.2.5 on 2025-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
